"""empty message

Revision ID: 33cada81c614
Revises: fc72fde5333c
Create Date: 2023-04-25 00:55:13.634267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cada81c614'
down_revision = 'fc72fde5333c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_upload', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('galleries', schema=None) as batch_op:
        batch_op.drop_column('type_upload')

    # ### end Alembic commands ###
